name: Android CI/CD with BrowserStack

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add steps to build your Android app here
      # Example:
      # - name: Set up JDK
      #   uses: actions/setup-java@v2
      #   with:
      #     java-version: '11'
      #     distribution: 'adopt'
      #
      # - name: Build APK
      #   run: ./gradlew assembleRelease

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-apk
          path: calculator-7-8-271241277.apk

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload APK to BrowserStack
        run: |
          curl -u "${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESS_KEY }}" \
               -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
               -F "file=@calculator-7-8-271241277.apk"
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
